# Generated by Django 3.2.9 on 2021-12-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=200)),
                ('data', models.JSONField()),
                ('result', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
